# Generated by Django 4.2.6 on 2024-07-21 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bungalow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('nb_pers', models.IntegerField(default=0)),
                ('caution_total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('nom', models.CharField(max_length=16)),
                ('prenom', models.CharField(max_length=16)),
                ('promo', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('V', 'vieux')], default='1A', max_length=2)),
                ('filier', models.CharField(choices=[('SN', 'SN'), ('3EA', '3EA'), ('MF2E', 'MF2E')], default='SN', max_length=4)),
                ('cautisant', models.BooleanField(default=False)),
                ('prix_place', models.FloatField(blank=True, null=True)),
                ('paiement', models.CharField(choices=[('L', 'Lydia'), ('V', 'virement'), ('C', 'chèque'), ('E', 'espèce'), ('N', 'non-payé')], default='N', max_length=1)),
                ('caution', models.CharField(choices=[('L', 'Lydia'), ('V', 'virement'), ('C', 'chèque'), ('E', 'espèce'), ('N', 'non-payé')], default='N', max_length=1)),
                ('valeur_caution', models.FloatField(default=100.0)),
                ('staffeur', models.CharField(choices=[('N', 'non'), ('A', 'AE'), ('C', 'can7'), ('T', 'tvn7'), ('P', 'photo7'), ('F', 'fanfare')], default='N', max_length=1)),
                ('date_paiement_place', models.DateTimeField(blank=True, null=True)),
                ('date_paiement_caution', models.DateTimeField(blank=True, null=True)),
                ('date_rendu_caution', models.DateTimeField(blank=True, null=True)),
                ('bungalow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inscr.bungalow')),
            ],
        ),
    ]
