# Generated by Django 4.2.6 on 2024-07-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrit',
            name='decharge_signe',
            field=models.BooleanField(default=False),
        ),
    ]
