# Generated by Django 4.2.6 on 2024-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscr', '0002_inscrit_decharge_signe'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrit',
            name='code_billet',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='commentaires',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='staff_caisse_caution',
            field=models.CharField(default='A. Bongiovanni', max_length=32),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='staff_caisse_place',
            field=models.CharField(default='A. Bongiovanni', max_length=32),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='nom',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='prenom',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='staffeur',
            field=models.CharField(choices=[('N', 'non'), ('A', 'AE'), ('C', 'can7'), ('T', 'tvn7'), ('P', 'photo7')], default='N', max_length=1),
        ),
    ]
