# Generated by Django 4.2.6 on 2024-08-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscr', '0003_inscrit_code_billet_inscrit_commentaires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrit',
            name='caution',
            field=models.CharField(choices=[('L', 'Lydia'), ('V', 'Virement'), ('C', 'Chèque'), ('E', 'Espèce'), ('N', 'Non-payé')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='paiement',
            field=models.CharField(choices=[('L', 'Lydia'), ('V', 'Virement'), ('C', 'Chèque'), ('E', 'Espèce'), ('N', 'Non-payé')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='staff_caisse_caution',
            field=models.CharField(blank=True, default='A. Bongiovanni', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='staff_caisse_place',
            field=models.CharField(blank=True, default='A. Bongiovanni', max_length=32, null=True),
        ),
    ]
