# Generated by Django 4.2.6 on 2024-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscr', '0004_alter_inscrit_caution_alter_inscrit_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrit',
            name='caution_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='place_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='caution',
            field=models.CharField(choices=[('L', 'Lydia'), ('V', 'Virement'), ('C', 'Chèque'), ('E', 'Espèce')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='paiement',
            field=models.CharField(choices=[('L', 'Lydia'), ('V', 'Virement'), ('C', 'Chèque'), ('E', 'Espèce')], default='L', max_length=1),
        ),
    ]
