# Generated by Django 4.2.6 on 2024-08-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscr', '0006_alter_inscrit_caution_alter_inscrit_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrit',
            name='caution',
            field=models.CharField(blank=True, choices=[('L', 'Lydia'), ('C', 'Chèque'), ('E', 'Espèce')], max_length=1),
        ),
    ]
