# Generated by Django 4.2.6 on 2024-08-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscr', '0007_alter_inscrit_caution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrit',
            name='username',
        ),
    ]
