# Generated by Django 4.2.6 on 2024-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscr', '0008_remove_inscrit_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrit',
            name='staffeur',
        ),
        migrations.AddField(
            model_name='inscrit',
            name='type_billet',
            field=models.CharField(choices=[('N', 'non-cotisant'), ('O', 'Cotisant'), ('A', 'AE'), ('C', 'can7'), ('T', 'tvn7'), ('P', 'photo7')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='filier',
            field=models.CharField(choices=[('SN', 'SN'), ('3EA', '3EA'), ('MF2E', 'MF2E'), ('AUX', 'Autres')], default='SN', max_length=4),
        ),
    ]
