# Generated by Django 4.2.6 on 2024-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscr', '0009_remove_inscrit_staffeur_inscrit_type_billet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrit',
            name='staff_caisse_caution',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='staff_caisse_place',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
