# Generated by Django 4.2.6 on 2024-09-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscr', '0010_alter_inscrit_staff_caisse_caution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrit',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
    ]
